/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginFrame.java
 *
 * Created on 16 Μαρ 2011, 1:18:32 μμ
 */
package GUI;

import entities.Credentials;
import sql.*;
import mail.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import util.MesDial;

/**
 * The login frame for the application. It's used to connect to the DBMS and to
 * mail server also.
 *
 * @author Alex Hughes
 */
public class LoginFrame extends GUI {

    public DBCredentials dbCre;
    public MailCred mlCre;
    private Connector c;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {

        initComponents();
        Credentials temp = Credentials.loadCredentials("DBCredentials.dat");
        Credentials temp1 = Credentials.loadCredentials("MailCredentials.dat");

        if (temp != null) {
            dbCre = (DBCredentials) temp;
            loadDBCredentials();
        }
        if (temp1 != null) {
            mlCre = (MailCred) temp1;
            loadMailCredentials();
        }
        
        super.setFrameLocationCenter(this);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StatusPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        dbUserField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dbPassField = new javax.swing.JPasswordField();
        dbUrlField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dbSchemaField = new javax.swing.JTextField();
        passOKButton = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        rememberMeCheckBox = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        mlFromField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mlUserField = new javax.swing.JTextField();
        mlPassField = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hug4Dogs Database (Java - MySQL)");
        setMinimumSize(new java.awt.Dimension(428, 280));
        setName("LoginFrame"); // NOI18N

        StatusPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Java - MySQL MailSender. Developed by Alex Hughes <alexhughes117@gmail.com>");

        javax.swing.GroupLayout StatusPanelLayout = new javax.swing.GroupLayout(StatusPanel);
        StatusPanel.setLayout(StatusPanelLayout);
        StatusPanelLayout.setHorizontalGroup(
            StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addContainerGap())
        );
        StatusPanelLayout.setVerticalGroup(
            StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Database Credentials"));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dbUserField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dbUserField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbUserFieldMouseClicked(evt);
            }
        });
        dbUserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbUserFieldActionPerformed(evt);
            }
        });
        dbUserField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dbUserFieldKeyPressed(evt);
            }
        });

        jLabel5.setText("username:");

        jLabel6.setText("password:");

        dbPassField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dbPassField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbPassFieldMouseClicked(evt);
            }
        });
        dbPassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dbPassFieldKeyPressed(evt);
            }
        });

        dbUrlField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dbUrlField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbUrlFieldMouseClicked(evt);
            }
        });
        dbUrlField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dbUrlFieldKeyPressed(evt);
            }
        });

        jLabel7.setText("url:");

        jLabel2.setText("schema (database):");

        dbSchemaField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbSchemaFieldMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dbUrlField)
                    .addComponent(dbSchemaField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dbPassField)
                    .addComponent(dbUserField))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbUrlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dbSchemaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dbUserField.getAccessibleContext().setAccessibleName("usernameTextField");
        dbPassField.getAccessibleContext().setAccessibleName("passwordTextField");
        dbUrlField.getAccessibleContext().setAccessibleName("dbmsURLTextField");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("CredentialsPanel");

        passOKButton.setText("OK");
        passOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passOKButtonActionPerformed(evt);
            }
        });
        passOKButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passOKButtonKeyPressed(evt);
            }
        });

        exitBtn.setText("Quit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        rememberMeCheckBox.setText("Remember Credentials");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Email Credentials"));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("from address:");

        jLabel9.setText("username:");

        mlPassField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mlPassField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mlPassFieldMouseClicked(evt);
            }
        });
        mlPassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mlPassFieldKeyPressed(evt);
            }
        });

        jLabel10.setText("password:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mlUserField, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(mlFromField)
                    .addComponent(mlPassField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(mlFromField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mlUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mlPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(passOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rememberMeCheckBox)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passOKButton)
                    .addComponent(exitBtn)
                    .addComponent(rememberMeCheckBox))
                .addGap(18, 18, 18)
                .addComponent(StatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dbUserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbUserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbUserFieldActionPerformed

    private void passOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passOKButtonActionPerformed
        okButton();
    }//GEN-LAST:event_passOKButtonActionPerformed

    private void dbPassFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dbPassFieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            okButton();
        }
    }//GEN-LAST:event_dbPassFieldKeyPressed

    private void dbUserFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dbUserFieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            okButton();
        }
    }//GEN-LAST:event_dbUserFieldKeyPressed

    private void dbUrlFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dbUrlFieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            okButton();
        }
    }//GEN-LAST:event_dbUrlFieldKeyPressed

    private void passOKButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passOKButtonKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            okButton();
        }
    }//GEN-LAST:event_passOKButtonKeyPressed

private void dbUrlFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbUrlFieldMouseClicked
    if (evt.getButton() == evt.BUTTON3) {
        popupMenuField(dbUrlField);
    }
}//GEN-LAST:event_dbUrlFieldMouseClicked

private void dbUserFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbUserFieldMouseClicked
    if (evt.getButton() == evt.BUTTON3) {
        popupMenuField(dbUserField);
    }
}//GEN-LAST:event_dbUserFieldMouseClicked

private void dbPassFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbPassFieldMouseClicked
}//GEN-LAST:event_dbPassFieldMouseClicked

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void dbSchemaFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbSchemaFieldMouseClicked
        if (evt.getButton() == evt.BUTTON3) {
            popupMenuField(dbUserField);
        }
    }//GEN-LAST:event_dbSchemaFieldMouseClicked

    private void mlPassFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mlPassFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mlPassFieldMouseClicked

    private void mlPassFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mlPassFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mlPassFieldKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StatusPanel;
    private javax.swing.JPasswordField dbPassField;
    private javax.swing.JTextField dbSchemaField;
    private javax.swing.JTextField dbUrlField;
    private javax.swing.JTextField dbUserField;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField mlFromField;
    private javax.swing.JPasswordField mlPassField;
    private javax.swing.JTextField mlUserField;
    private javax.swing.JButton passOKButton;
    private javax.swing.JCheckBox rememberMeCheckBox;
    // End of variables declaration//GEN-END:variables

    private void getInfo() {

        char[] dbPasswordC = dbPassField.getPassword();
        char[] mlPasswordC = mlPassField.getPassword();

        dbCre = new DBCredentials(dbUrlField.getText(),
                dbUserField.getText(), new String(dbPasswordC),
                dbSchemaField.getText());

        mlCre = new MailCred(mlFromField.getText(), mlUserField.getText(),
                new String(mlPasswordC));
    }

    private void loadDBCredentials() {
        dbUrlField.setText(dbCre.getURL());
        dbUserField.setText(dbCre.getUsername());
        dbPassField.setText(dbCre.getPassword());
        dbSchemaField.setText(dbCre.getSchema());
    }
    
    private void loadMailCredentials(){
        mlFromField.setText(mlCre.getFromAddress());
        mlUserField.setText(mlCre.getUsername());
        mlPassField.setText(mlCre.getPassword());
    }

    private void okButton() {
        LoadingForm l = new LoadingForm();
        this.setVisible(false);
        getInfo();
        Connector c;
        try {
            c = new Connector(dbCre);

            if (rememberMeCheckBox.isSelected()) {
                Credentials.saveCredentials(dbCre);
                Credentials.saveCredentials(mlCre);
            }
            
            l.dispose();
            this.dispose();
        } catch (SQLException ex) {
            l.dispose();
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
            MesDial.conError(this);
            this.setVisible(true);
        } catch (ClassNotFoundException ex) {
            l.dispose();
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
            MesDial.conError(this);
            this.setVisible(true);
        }
    }
}
